name: equipharm
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - rdkit
  - numpy<2
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - ase
  - tensorboard
  - jupyterlab
  - ipykernel

  - pip:
      # PyTorch with CUDA 12.8 for Blackwell GPUs
      - --index-url=https://download.pytorch.org/whl/cu128
      - torch==2.7.0
      - torchvision==0.22.0
      - torchaudio==2.7.0

      # return to normal PyPI for the rest
      - --extra-index-url=https://pypi.org/simple

      # PyTorch Geometric
      - torch-geometric

      # Model libraries
      - equiformer-pytorch
      - se3-transformer-pytorch
      - dive-into-graphs