name: equipharm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.*
  - pytorch-cuda=11.8 
  - rdkit
  - numpy<2
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - ase
  - tensorboard
  - jupyterlab
  - ipykernel
  - pip:
      - --find-links=https://data.pyg.org/whl/torch-2.0.0+cu118.html  # for CUDA 11.8
      - torch-geometric==2.5.1
      - torch-scatter
      - torch-sparse
      - torch-cluster
      - torch-spline-conv
      - equiformer-pytorch
      - se3-transformer-pytorch
      - dive-into-graphs
