name: /data/db6/Izzy/EquiPharm/equipharm
channels:
  - conda-forge
dependencies:
  - ase
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy[version='<2']
  - pandas
  - pip
  - python=3.10
  - rdkit
  - scikit-learn
  - scipy
  - tensorboard
  - tqdm
  - cmake
  - compilers
  - make
  - boost-cpp
  - openbabel
  - jsoncpp
  - eigen
  - lemon
  - curl
  - gperftools
  - libcurl
  - pkg-config
  - fcgi2
  - ann
  - autoconf
  - automake
  - libtool
  - m4
  - perl
  - coin-or-cbc
  - coin-or-clp
